/**
 * Configuración de todos los modelos 3D del Museo Virtual
 * Este archivo centraliza la posición, rotación, escala y propiedades de cada modelo
 */

const museumModelsConfig = {
  assets: {
    models3D: [
      { id: 'furina', key: 'furina' },
      { id: 'volcan', key: 'volcan' },
      { id: 'catedral', key: 'catedral' },
      { id: 'donkey_sillar_polycam', key: 'donkey_sillar_polycam' },
      { id: 'eagle_sillar_polycam', key: 'eagle_sillar_polycam' },
      { id: 'barroco_andino', key: 'barroco_andino' },
      { id: 'sillar_plycam_1', key: 'sillar_plycam_1' },
    ],
    textures: [
      { id: 'podiums-texture', key: 'podiumsTexture' },
      { id: 'lamps-texture', key: 'lampsTexture' },
      { id: 'moonlight-texture', key: 'moonlightTexture' },
      { id: 'catedralPhoto', key: 'catedralPhoto' },
      { id: 'volcanPhoto', key: 'volcanPhoto' },
      { id: 'miradorPhoto', key: 'miradorPhoto' },
      { id: 'volcanPhoto2', key: 'volcanPhoto2' },
      { id: 'plazaPhoto', key: 'plazaPhoto' },
      { id: 'sillarPhoto', key: 'sillarPhoto' },
      { id: 'rocotoPhoto', key: 'rocotoPhoto' },
      { id: 'plazaPhoto2', key: 'plazaPhoto2' },
      { id: 'sillarPhoto2', key: 'sillarPhoto2' },
      { id: 'sillarPhoto3', key: 'sillarPhoto3' },
      { id: 'vallePhoto', key: 'vallePhoto' },
      { id: 'vallePhoto2', key: 'vallePhoto2' },
    ],
    objModels: [
      { id: 'podiums-obj', key: 'podiumsModel' },
      { id: 'lamps-obj', key: 'lampsModel' },
      { id: 'recuadro-obj', key: 'recuadroModel' },
    ],
  },

  models3D: [
    {
      id: 'furina',
      type: 'gltf',
      model: '#furina',
      position: { x: -10, y: 0.7, z: -9 },
      rotation: { x: 0, y: 90, z: 0 },
      scale: { x: 1.3, y: 1.3, z: 1.3 },
      staticBody: true,
      description: 'Modelo 3D de Furina',
    },
    {
      id: 'volcan',
      type: 'gltf',
      model: '#volcan',
      position: { x: -10.2, y: 0.6, z: -12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 0.015, y: 0.015, z: 0.015 },
      staticBody: true,
      description: 'Modelo 3D del Volcán Misti',
    },
    {
      id: 'catedral',
      type: 'gltf',
      model: '#catedral',
      position: { x: 10, y: 1.8, z: -5 },
      rotation: { x: 0, y: 180, z: 0 },
      scale: { x: 3, y: 3, z: 3 },
      staticBody: true,
      description: 'Modelo 3D de la Catedral de Arequipa',
    },
    {
      id: 'donkey_sillar',
      type: 'gltf',
      model: '#donkey_sillar_polycam',
      position: { x: 9.2, y: 0.99, z: 7 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 2, y: 2, z: 2 },
      staticBody: true,
      description: 'Burro tallado en sillar',
    },
    {
      id: 'eagle_sillar',
      type: 'gltf',
      model: '#eagle_sillar_polycam',
      position: { x: 9.7, y: 1.2, z: 4 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 2, y: 2, z: 2 },
      staticBody: true,
      description: 'Águila tallada en sillar',
    },
    {
      id: 'barroco_andino',
      type: 'gltf',
      model: '#barroco_andino',
      position: { x: -9.7, y: 1.7, z: 10 },
      rotation: { x: 0, y: 270, z: 0 },
      scale: { x: 0.6, y: 0.6, z: 0.6 },
      staticBody: true,
      description: 'Portal barroco andino',
    },
    {
      id: 'sillar_plycam',
      type: 'gltf',
      model: '#sillar_plycam_1',
      position: { x: 9.5, y: 1.6, z: 11 },
      rotation: { x: 0, y: 180, z: 0 },
      scale: { x: 4, y: 4, z: 4 },
      staticBody: true,
      description: 'Escultura de sillar',
    },
  ],

  // ==================== PODIUMS (PEDESTALES) ====================
  podiums: [
    {
      id: 'podium_1',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: 13, y: 0, z: 12.1 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_2',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: 10, y: 0, z: 12.1 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_3',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: -13, y: 0, z: 12.1 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_4',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: -10, y: 0, z: 12.1 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_5',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: -5, y: 0, z: 6 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_6',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: -5, y: 0, z: 10 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_7',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: 0, y: 0, z: 6 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_8',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: 0, y: 0, z: 10 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_9',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: 5, y: 0, z: 6 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'podium_10',
      type: 'obj',
      objModel: '#podiums-obj',
      material: '#podiums-texture',
      position: { x: 5, y: 0, z: 10 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
  ],

  // ==================== LÁMPARAS ====================
  lamps: [
    {
      id: 'lamp_1',
      type: 'obj',
      objModel: '#lamps-obj',
      material: '#lamps-texture',
      position: { x: 12, y: 0, z: -12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'lamp_2',
      type: 'obj',
      objModel: '#lamps-obj',
      material: '#lamps-texture',
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'lamp_3',
      type: 'obj',
      objModel: '#lamps-obj',
      material: '#lamps-texture',
      position: { x: -12.7, y: 0, z: -12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
    {
      id: 'lamp_4',
      type: 'obj',
      objModel: '#lamps-obj',
      material: '#lamps-texture',
      position: { x: -10, y: 0, z: -12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
    },
  ],

  // ==================== CUADROS/FOTOGRAFÍAS ====================
  frames: [
    {
      id: 'frame_sillar3',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#sillarPhoto3',
      position: { x: -7.2, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Canteras del Sillar Paisaje',
    },
    {
      id: 'frame_sillar2',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#sillarPhoto2',
      position: { x: -6.2, y: -0.2, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 0.7, y: 1.1, z: 1 },
      staticBody: true,
      description: 'Escultura de sillar en la cantera',
    },
    {
      id: 'frame_rocoto',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#rocotoPhoto',
      position: { x: 18.8, y: -0.2, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1.21, y: 1.1, z: 1 },
      staticBody: true,
      description: 'Rocoto Relleno',
    },
    {
      id: 'frame_sillar',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#sillarPhoto',
      position: { x: 1, y: 0, z: 12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Canteras del Sillar',
    },
    {
      id: 'frame_volcan2',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#volcanPhoto2',
      position: { x: 3.3, y: 0, z: 12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Campiña de Arequipa con el Misti',
    },
    {
      id: 'frame_catedral',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#catedralPhoto',
      position: { x: 5.6, y: 0, z: 12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Catedral de Arequipa en la Tarde',
    },
    {
      id: 'frame_volcan',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#volcanPhoto',
      position: { x: 7.9, y: 0, z: 12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Volcán Misti',
    },
    {
      id: 'frame_mirador',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#miradorPhoto',
      position: { x: 10.2, y: 0, z: 12 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Mirador de Yanahuara',
    },
    {
      id: 'frame_moonlight',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#moonlight-texture',
      position: { x: -7.2, y: 0, z: -12 },
      rotation: { x: 0, y: 180, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Vista nocturna',
    },
    {
      id: 'frame_valle',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#vallePhoto',
      position: { x: -4.9, y: 0, z: -12 },
      rotation: { x: 0, y: 180, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Valle de Arequipa',
    },
    {
      id: 'frame_valle2',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#vallePhoto2',
      position: { x: -9.5, y: 0, z: -12 },
      rotation: { x: 0, y: 180, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Campiña de Arequipa',
    },
    {
      id: 'frame_plaza2',
      type: 'obj',
      objModel: '#recuadro-obj',
      material: '#plazaPhoto2',
      position: { x: -2.6, y: 0, z: -12 },
      rotation: { x: 0, y: 180, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      staticBody: true,
      description: 'Plaza de Armas de Arequipa',
    },
  ],

  // ==================== SISTEMA DE ILUMINACIÓN ====================
  lights: {
    // Luces principales del museo
    ambient: {
      type: 'ambient',
      color: '#FFF',
      intensity: 0.6,
    },
    directional: [
      {
        id: 'main_directional',
        type: 'directional',
        color: '#FFF',
        intensity: 0.5,
        position: { x: 2, y: 20, z: 0 },
      },
      {
        id: 'front_directional',
        type: 'directional',
        color: '#FFF',
        intensity: 1,
        position: { x: 2, y: 4, z: -3 },
      },
    ],
    // Luces decorativas puntuales
    point: [
      // Zona frontal (cerca de la entrada)
      { id: 'point_front_left', color: '#FFFFFF', intensity: 1.2, position: { x: -10, y: 3.5, z: -12 } },
      { id: 'point_front_right', color: '#FFFFFF', intensity: 1.2, position: { x: 10, y: 3.5, z: -12 } },
      
      // Zona trasera
      { id: 'point_back_center', color: '#FFFFFF', intensity: 1.0, position: { x: 0, y: 3.5, z: 12 } },
      { id: 'point_back_left', color: '#FFFFFF', intensity: 1.0, position: { x: -10, y: 3.5, z: 10 } },
      { id: 'point_back_right', color: '#FFFFFF', intensity: 1.0, position: { x: 10, y: 3.5, z: 10 } },
      
      // Zonas laterales
      { id: 'point_left_wall', color: '#FFFFFF', intensity: 0.8, position: { x: -14, y: 3, z: 0 } },
      { id: 'point_right_wall', color: '#FFFFFF', intensity: 0.8, position: { x: 14, y: 3, z: 0 } },
      
      // Luces sobre modelos principales
      { id: 'spot_catedral', color: '#FFFFFF', intensity: 1.5, position: { x: 10, y: 4, z: -5 } },
      { id: 'spot_portal', color: '#FFFFFF', intensity: 1.5, position: { x: -10, y: 4, z: 10 } },
      { id: 'spot_furina', color: '#FFFFFF', intensity: 1.2, position: { x: -10, y: 3, z: -9 } },
      
      // Iluminación central
      { id: 'center_top', color: '#FFFFFF', intensity: 1.0, position: { x: 0, y: 5, z: 0 } },
      
      // Acentos en esquinas
      { id: 'corner_ne', color: '#FFFFFF', intensity: 0.7, position: { x: 12, y: 2.5, z: -10 } },
      { id: 'corner_nw', color: '#FFFFFF', intensity: 0.7, position: { x: -12, y: 2.5, z: -10 } },
      { id: 'corner_se', color: '#FFFFFF', intensity: 0.7, position: { x: 12, y: 2.5, z: 10 } },
      { id: 'corner_sw', color: '#FFFFFF', intensity: 0.7, position: { x: -12, y: 2.5, z: 10 } },
    ],
    // Luces spot (simuladas con point de alta intensidad)
    spot: [
      { id: 'gallery_light_1', color: '#FFFFFF', intensity: 2, position: { x: -4, y: 4, z: -12 }, distance: 8 },
      { id: 'gallery_light_2', color: '#FFFFFF', intensity: 2, position: { x: 4, y: 4, z: -12 }, distance: 8 },
      { id: 'gallery_light_3', color: '#FFFFFF', intensity: 2, position: { x: -4, y: 4, z: 12 }, distance: 8 },
      { id: 'gallery_light_4', color: '#FFFFFF', intensity: 2, position: { x: 4, y: 4, z: 12 }, distance: 8 },
    ],
  },

  // ==================== ELEMENTOS DECORATIVOS ====================
  decorations: {
    spheres: [
      { id: 'sphere_nw', radius: 0.3, color: '#E0E0E0', position: { x: -14, y: 1.5, z: -10 }, metalness: 0.8, roughness: 0.2 },
      { id: 'sphere_ne', radius: 0.3, color: '#D3D3D3', position: { x: 14, y: 1.5, z: -10 }, metalness: 0.8, roughness: 0.2 },
      { id: 'sphere_sw', radius: 0.3, color: '#C0C0C0', position: { x: -14, y: 1.5, z: 10 }, metalness: 0.8, roughness: 0.2 },
      { id: 'sphere_se', radius: 0.3, color: '#B8B8B8', position: { x: 14, y: 1.5, z: 10 }, metalness: 0.8, roughness: 0.2 },
      { id: 'sphere_center', radius: 0.4, color: '#FFFFFF', position: { x: 0, y: 2, z: 0 }, metalness: 0.9, roughness: 0.1 },
    ],
    boxes: [
      { id: 'pedestal_nw', size: { x: 0.5, y: 1, z: 0.5 }, color: '#8B4513', position: { x: -12, y: 0.5, z: -8 }, roughness: 0.7 },
      { id: 'pedestal_ne', size: { x: 0.5, y: 1, z: 0.5 }, color: '#8B4513', position: { x: 12, y: 0.5, z: -8 }, roughness: 0.7 },
      { id: 'pedestal_sw', size: { x: 0.5, y: 1, z: 0.5 }, color: '#8B4513', position: { x: -12, y: 0.5, z: 8 }, roughness: 0.7 },
      { id: 'pedestal_se', size: { x: 0.5, y: 1, z: 0.5 }, color: '#8B4513', position: { x: 12, y: 0.5, z: 8 }, roughness: 0.7 },
    ],
    cylinders: [
      { id: 'column_left', radius: 0.2, height: 2, color: '#D3D3D3', position: { x: -15, y: 1, z: 0 }, metalness: 0.5 },
      { id: 'column_right', radius: 0.2, height: 2, color: '#D3D3D3', position: { x: 15, y: 1, z: 0 }, metalness: 0.5 },
      { id: 'column_front', radius: 0.2, height: 2.5, color: '#C0C0C0', position: { x: 0, y: 1.25, z: -15 }, metalness: 0.5 },
      { id: 'column_back', radius: 0.2, height: 2.5, color: '#C0C0C0', position: { x: 0, y: 1.25, z: 15 }, metalness: 0.5 },
    ],
  },

  // ==================== ZONAS DE INTERACCIÓN (Para detección de modelos) ====================
  interactionZones: [
    // Imágenes del muro norte (expandidas para mejor detección)
    { id: 1, name: 'Imagen del Cañon del Colca', bounds: { xMin: -6, xMax: -2, zMin: -15, zMax: -11 } },
    { id: 2, name: 'Imagen de la plaza de armas', bounds: { xMin: -3, xMax: 0, zMin: -15, zMax: -11 } },
    { id: 3, name: 'Imagen de la campiña y Misti', bounds: { xMin: -0.5, xMax: 2.5, zMin: -15, zMax: -11 } },
    { id: 4, name: 'Imagen alternativa de la plaza', bounds: { xMin: 1.5, xMax: 4.5, zMin: -15, zMax: -11 } },
    
    // Imágenes del muro sur (expandidas)
    { id: 5, name: 'Imagen del mirador', bounds: { xMin: 3, xMax: 6.5, zMin: 11, zMax: 15 } },
    { id: 6, name: 'Imagen del volcán Misti', bounds: { xMin: 0.5, xMax: 4, zMin: 11, zMax: 15 } },
    { id: 7, name: 'Imagen de la catedral', bounds: { xMin: -1.5, xMax: 1.5, zMin: 11, zMax: 15 } },
    { id: 8, name: 'Imagen de la campiña', bounds: { xMin: -4, xMax: 1, zMin: 11, zMax: 15 } },
    { id: 9, name: 'Imagen de las canteras de sillar', bounds: { xMin: -6.5, xMax: -3, zMin: 11, zMax: 15 } },
    
    // Imágenes del muro este (expandidas)
    { id: 10, name: 'Imagen del rocoto relleno', bounds: { xMin: 9.5, xMax: 14, zMin: -0.5, zMax: 2.5 } },
    
    // Imágenes del muro oeste (expandidas)
    { id: 11, name: 'Imagen lateral de las canteras de sillar', bounds: { xMin: -11.5, xMax: -8.5, zMin: -0.5, zMax: 2.5 } },
    { id: 12, name: 'Imagen lateral de la cantera', bounds: { xMin: -15, xMax: -10.5, zMin: -0.5, zMax: 2.5 } },
    
    // Modelos 3D del lado este (área más grande para interacción intuitiva)
    { id: 13, name: 'Modelo 3D de la catedral', bounds: { xMin: 6, xMax: 11, zMin: -7.5, zMax: -2 } },
    { id: 14, name: 'Modelo 3D del águila', bounds: { xMin: 6, xMax: 11, zMin: 1.5, zMax: 6 } },
    { id: 15, name: 'Modelo 3D del burro', bounds: { xMin: 6, xMax: 11, zMin: 5, zMax: 9 } },
    { id: 16, name: 'Modelo 3D de la mujer', bounds: { xMin: 6, xMax: 11, zMin: 7, zMax: 11 } },
    { id: 17, name: 'Modelo 3D del hombre', bounds: { xMin: 6, xMax: 11, zMin: 9.5, zMax: 13.5 } },
    
    // Modelos 3D del lado oeste (área ampliada)
    { id: 18, name: 'Modelo 3D del portal', bounds: { xMin: -11, xMax: -6.5, zMin: 8, zMax: 13 } },
    { id: 19, name: 'Modelo 3D de Furina', bounds: { xMin: -11, xMax: -6.5, zMin: -11, zMax: -7 } },
    { id: 20, name: 'Modelo 3D del Misti', bounds: { xMin: -11, xMax: -6.5, zMin: -14, zMax: -10 } },
  ],
};

export default museumModelsConfig;
